### ISSUE TITLE
Не верное отоброжение версии сборки в HACS

### ISSUE THREAD

**Issue by dima81rus** [RealLord/tion_home_assistant#2]
![изображение](https://github.com/RealLord/tion_home_assistant/assets/98762195/015c0810-a797-43b0-8823-42c2e1ff4056)

жить ни как не мешает, но скорее всего где-то релиз не дооформлен как версионный.

**Comment by RealLord** [comment]
> жить ни как не мешает, но скорее всего где-то релиз не дооформлен как версионный.

Сложно проверить, так как у меня обновление локальное, а не со своего репозитария, так как локальная разработка.
Добавил пару тегов в манифест, проверьте, стало лучше или нет?

**Comment by dima81rus** [comment]
похоже этого не достаточно или применяется после следующего релиза (я попробовал обновить и перекачать в HACS) :(
![изображение](https://github.com/RealLord/tion_home_assistant/assets/98762195/1e82f7b8-fc07-4092-b0e7-109a317835ef)

так же, возможно проблема в том, что с точки зрения гитхаба у вас нет релизов:
![изображение](https://github.com/RealLord/tion_home_assistant/assets/98762195/055204f7-6669-4bbd-9082-d246781d61c7)

**Comment by RealLord** [comment]
Ок, выпустил релиз на Git. 
Подождем пока кто-то еще напишет какой-нибудь баг, что проверить.

**Comment by dima81rus** [comment]
вот теперь заработало! супер :)
![изображение](https://github.com/RealLord/tion_home_assistant/assets/98762195/71c7b5e9-bb39-4115-9cd2-0a8a6baac5ba)

**Comment by RealLord** [comment]
Отлично, значит одной проблемой меньше!
